version: "3.8"
services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_password"
        MYSQL_PASSWORD_FILE: "/run/secrets/db_password"
        MYSQL_USER: "sholex"
        MYSQL_DATABASE: "lilsholex"
    secrets:
      - db_password
    healthcheck:
      test: mysqladmin -u root --password=`cat $MYSQL_ROOT_PASSWORD_FILE` ping
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 1m
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.db==true
      restart_policy:
        condition: any
        max_attempts: 3
        window: 20s
        delay: 10s
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: start-first
    networks:
      - db_django
    volumes:
    - type: volume
      source: db
      target: /var/lib/mysql
  nginx:
    image: ghcr.io/sholex-team/nginx:3.6
    networks:
      - nginx_lilsholex
      - internet
    healthcheck:
      test: python3.9 nginx.py
      interval: 30s
      timeout: 5s
      start_period: 1m
      retries: 3
    depends_on:
      - gunicorn
      - daphne
    volumes:
      - ./static:/root/static:ro
      - type: volume
        source: nginx
        target: /var/log/nginx
    deploy:
      replicas: 1
      placement:
        preferences:
          - spread: node.labels.zone
        constraints:
          - node.labels.nginx==true
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
        delay: 5s
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: stop-first
    secrets:
      - ssl_certificate
      - ssl_key
      - dhparam
    ports:
    - "443:443/tcp"
    - "80:80/tcp"
  gunicorn:
    image: ghcr.io/sholex-team/lilsholex:5.2
    networks:
      - db_django
      - nginx_lilsholex
      - internet
      - cache_django
    secrets:
      - db_password
      - persianmeme_channel
      - persianmeme_help_messages
      - persianmeme_token
      - secret_key
      - persianmeme_logs
      - persianmeme_messages
      - persianmeme_reports
    depends_on:
      - db
      - migrations
    healthcheck:
      test: python healthchecks/gunicorn.py
      interval: 30s
      timeout: 5s
      start_period: 1m
      retries: 3
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.webserver==true
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: stop-first
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
        delay: 5s
    volumes:
      - type: volume
        source: persianmeme
        target: /home/sholex/persianmeme/migrations
  tasks:
    image: ghcr.io/sholex-team/lilsholex:5.2
    command: bash -c "python manage.py clear_tasks && python manage.py process_tasks --sleep 15"
    networks:
      - db_django
      - internet
    secrets:
      - db_password
      - secret_key
      - persianmeme_token
      - persianmeme_channel
      - persianmeme_help_messages
      - persianmeme_logs
      - persianmeme_messages
      - persianmeme_reports
    depends_on:
      - db
      - migrations
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.task_master==true
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: start-first
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
        delay: 5s
    volumes:
      - type: volume
        source: persianmeme
        target: /home/sholex/persianmeme/migrations
  broadcasts:
    image: ghcr.io/sholex-team/lilsholex:5.2
    command: "python manage.py process_broadcasts"
    networks:
      - db_django
      - internet
    secrets:
      - db_password
      - secret_key
      - persianmeme_token
      - persianmeme_channel
      - persianmeme_help_messages
      - persianmeme_logs
      - persianmeme_messages
      - persianmeme_reports
    depends_on:
      - db
      - migrations
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.task_master==true
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: start-first
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
        delay: 5s
    volumes:
      - type: volume
        source: persianmeme
        target: /home/sholex/persianmeme/migrations
  memcached:
    image: memcached:1.6.12
    command: "memcached -m 256"
    networks:
      - cache_django
    deploy:
      replicas: 1
      placement:
        preferences:
          - spread: node.labels.zone
        constraints:
          - node.labels.cache==true
      restart_policy:
        condition: any
        max_attempts: 3
        window: 20s
        delay: 10s
      update_config:
        parallelism: 1
        delay: 2s
        failure_action: rollback
        monitor: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: start-first
  migrations:
    image: ghcr.io/sholex-team/lilsholex:5.2
    command: "bash -c 'yes | python manage.py makemigrations persianmeme background_task && \
    yes | python manage.py migrate && python manage.py collectstatic --noinput'"
    secrets:
      - db_password
      - secret_key
      - persianmeme_token
      - persianmeme_channel
      - persianmeme_help_messages
      - persianmeme_logs
      - persianmeme_messages
      - persianmeme_reports
    depends_on:
      - db
    networks:
      - db_django
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 10s
        delay: 15s
    volumes:
      - type: volume
        source: persianmeme
        target: /home/sholex/persianmeme/migrations
networks:
  db_django:
    driver: "overlay"
    name: "db_django"
    internal: true
  nginx_lilsholex:
    driver: "overlay"
    name: "nginx_lilsholex"
    internal: true
  internet:
    driver: "overlay"
    name: "internet"
  cache_django:
    driver: "overlay"
    name: "cache_django"
    internal: true
volumes:
  db:
    name: "db"
  persianmeme:
    name: "persianmeme"
  nginx:
    name: "nginx"
secrets:
  db_password:
    external: true
  persianmeme_channel:
    external: true
  persianmeme_token:
    external: true
  persianmeme_logs:
    external: true
  persianmeme_messages:
    external: true
  persianmeme_help_messages:
    file: secrets/help_messages.json
  persianmeme_reports:
    external: true
  secret_key:
    external: true
  ssl_certificate:
    file: ./ssl/fullchain.pem
  ssl_key:
    file: ./ssl/privkey.pem
  dhparam:
    file: ./ssl/dhparam.pem
  domain:
    external: true
